name: goreleaser

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - 
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
        id: go
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
